# Generated by Django 5.1.3 on 2024-11-20 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('arrendatario', 'Arrendatario'), ('arrendador', 'Arrendador')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela')], max_length=50),
        ),
        migrations.CreateModel(
            name='RegistroArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('aceptado', 'Aceptado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.inmueble')),
                ('usuario_arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriendos_ofrecidos', to='gestion_inmuebles.usuario')),
                ('usuario_arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriendos_solicitados', to='gestion_inmuebles.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioInmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.inmueble')),
                ('usuario_arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.usuario')),
            ],
            options={
                'unique_together': {('inmueble', 'usuario_arrendador')},
            },
        ),
    ]
